### ISSUE TITLE
?

### ISSUE THREAD

**Issue by MichaelZH24** [tzw0745/tumblr-crawler-cli#10]

**Comment by tzw0745** [comment]
`RequestException` may cause by any network error when downloading file, like `connection timeout`, `proxy error` etc. need more detail to know why.

**Comment by tzw0745** [comment]
[commit 1fe9f66](https://github.com/tzw0745/tumblr-crawler-cli/commit/1fe9f66bb5b89ab272b8b857e3b066b104abe049) pushed
please pull the latest code and run it again to see more detail.

**Comment by MichaelZH24** [comment]
The detail of "RequestException":
requests.packages.urllib3.exceptions.ReadTimeoutError: SOCKSHTTPConnectionPool(host='', port=443): Read timed out. (read timeout=3)

**Comment by tzw0745** [comment]
looks like network problem. if this error occurs frequently, please check your proxy and network.

**Comment by MichaelZH24** [comment]
okay, thx!

**Comment by MichaelZH24** [comment]
I set the timeout = 100 and solve this question. But there is a new question:
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
