### ISSUE TITLE
BUG：部分图片地址格式不一样造成正则匹配异常导致退出

### ISSUE THREAD

**Issue by keepsmilence** [tzw0745/tumblr-crawler-cli#11]
uid = re.findall(uid_reg, photo_url)[0][1]
这一行，当图片地址没有匹配到**tumblr_**时抛数组异常，导致任务结束；
tip，测试出问题的地址 migg1001

**Comment by tzw0745** [comment]
能给出出错链接或站点地址吗

**Comment by keepsmilence** [comment]
执行就报异常，大概运行到11.30的图片时就退出

**Comment by tzw0745** [comment]
commit [a693194](https://github.com/tzw0745/tumblr-crawler-cli/commit/a6931946a3787c26a49b55bf1fd2cde010e3f170)已提交。增加图片url兼容性。

**Comment by keepsmilence** [comment]
good，thx～
