### ISSUE TITLE
Suggestion for enhancement

### ISSUE THREAD

**Issue by winsoncky** [tzw0745/tumblr-crawler-cli#13]
Thanks for the effort on the tumblr-crawler-cli, after several try with it, I have some suggestion for enhancement. 

1. Suggest to have  a .txt file to list the name of tumblr site.

2. Suggest to allow the authentication so that the private site we can still use an account to do it.

**Comment by tzw0745** [comment]
tumblr-crawler-cli can process multiple site at the same time.
```shell
$ python tumblr-crawler.py site1 site2
```
you can easily use shell or clipboard to do that with .txt file.

**Comment by tzw0745** [comment]
tumblr api v1 don't support authentication, but tumblr api v2 need apply APPID first... so  dealing with private sites is a difficult problem
