### ISSUE TITLE
关于README

### ISSUE THREAD

**Issue by lotuslily** [tzw0745/tumblr-crawler-cli#2]
README里运行程序的命令里，程序名好像打错了。

**Comment by tzw0745** [comment]
抱歉，已更正

**Comment by fireattack** [comment]
Readme的图片，http://pictures.tzw0745.cn/18-9-29/13036783.jpg ，似乎在GitHub网页上会被再re-host一次，变成 

https://camo.githubusercontent.com/f4d7a67e888e785b68ce99755649c8d11c73ef22/687474703a2f2f70696374757265732e747a77303734352e636e2f31382d392d32392f31333033363738332e6a7067

但是我这里看这张图片是显示不全的，很奇怪

**Comment by tzw0745** [comment]
应该是GITHUB缓存+墙的问题。先前直连看图片会显示不全，切换成代理就显示正常。现在直连又没问题了。
