### ISSUE TITLE
获取图片url越界

### ISSUE THREAD

**Issue by onlyAPK** [tzw0745/tumblr-crawler-cli#4]
File "tumblr-crawler.py", line 106, in parse_site_thread
    uid = re.findall(r'tumblr_([a-zA-Z0-9]{15,})', photo_url)[0]
IndexError: list index out of range

加了个判断：
if re.findall(r'tumblr_([a-zA-Z0-9]{15,})', photo_url):
就没问题了

**Comment by tzw0745** [comment]
请问出错的photo_url是多少呢？

**Comment by onlyAPK** [comment]
不会py不会看log。。哈哈哈。是获取这个博主666convict的时候报错了。
命令行：python tumblr-crawler.py -x socks5h://127.0.0.1:1086 -p 666convict
你试一下看看
公然开车了
最后，万分感谢你的代码

**Comment by tzw0745** [comment]
已更新代码，支持inline格式图片url。
[commit 919b7e2](https://github.com/tzw0745/tumblr-crawler-cli/commit/919b7e2064e8c6bfe46b3979b457cb730aa86bab)

**Comment by onlyAPK** [comment]
万分感谢
