### ISSUE TITLE
视频抓取有遗漏

### ISSUE THREAD

**Issue by Mondobongoo** [tzw0745/tumblr-crawler-cli#5]
首先非常感谢你的代码！(趁着tumblr还没有完全关，赶紧备份……)
图片抓取应该没什么问题（也可能是我暂时没有检查出来）
但是可以发现视频抓取有遗漏
执行代码
`python tumblr-crawler.py --video wanimal1983`
抓取的视频共有25个，而实际上从以下地址看到所有的视频
`http://wanimal1983.org/archive/filter-by/video`
我数了数共有48个，遗漏了不少，请问是什么原因导致的？

**Comment by tzw0745** [comment]
本工具只能提取以标准姿势上传到tumblr上的视频，`wanimal1983`这个站点的很多视频实际上是以外链的形式存在的，所以下载不了。

**Comment by zzzop** [comment]
转发的应该也在achive这个页面里
